export const CHAT_CONSTANTS = {
  GET_USER_DATA: '@chat/GET_USER_DATA',
  USERS_FOUND: '@chat/USERS_FOUND',
  SET_CURRENT_CHAT: '@chat/SET_CURRENT_CHAT',
  SEND_MSG_TO_USER: '@chat/SEND_MSG_TO_USER',
  USER_MSG_FROM_SERVER: '@chat/USER_MSG_FROM_SERVER',
  SET_SOCKET_CLIENT: '@chat/SET_SOCKET_CLIENT',
  CLEAN_CHAT_SESSION: '@chat/CLEAN_CHAT_SESSION',
}
